language: node_js

node_js:
  - '8'

addons:
  postgresql: "9.5"

services:
  - postgresql
  - redis-server

env:
  - POSTGRESQL_DATABASE=travis_ci_test
  - POSTGRESQL_USER=postgres
  - POSTGRESQL_HOST=localhost
  - POSTGRESQL_PORT=5432
  - REDIS_HOST=localhost
  - REDIS_PORT=6379

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - npm install -g lerna eslint db-migrate
  - lerna bootstrap

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'select version();' -U postgres
  - cd src/gladys-gateway-server && db-migrate up && cd ../..

script:
  - lerna run eslint
  - lerna run test

env:
  - CXX=g++-4.8
