language: node_js

node_js:
  - '8'

addons:
  postgresql: '9.6'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql
  - redis-server

env:
  global:
    - POSTGRESQL_DATABASE=travis_ci_test
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_HOST=localhost
    - POSTGRESQL_PASSWORD=
    - POSTGRESQL_PORT=5432
    - REDIS_HOST=localhost
    - REDIS_PORT=6379
    - MAILGUN_API_KEY=test
    - MAILGUN_DOMAIN=test.mailgun.org
    - EMAIL_FROM="Gladys Project <test.mailgun.org>"
    - CXX=g++-4.8

before_install:
  - npm install -g lerna eslint db-migrate
  - lerna bootstrap

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'select version();' -U postgres
  - cd src/gladys-gateway-server && db-migrate up && cd ../..

script:
  - lerna run eslint
  - lerna run test